### ISSUE TITLE
Disable messages

### ISSUE THREAD

**Issue by rainerborene** [wikitopian/hardmode#9] opened 2013-02-14 19:59 UTC
It would be great to provide an option to disable messages.

**Comment by ghost** [comment] 2013-02-14 21:52
Working on it now, will add a pull request soon

**Comment by ghost** [comment] 2013-02-14 22:04
Tadaa #10

**Comment by wikitopian** [comment] 2013-02-14 23:39
Excellent job, @xeross!

**Comment by wikitopian** [comment] 2013-02-14 23:40
Duplicate of #4, closed by @xeross

**Closed as completed** 2013-02-14 23:39 UTC
Labels: duplicate
